@base_url = http://localhost:8087
@user_id = 6164c296-9248-431a-8e5f-4a761c27ccc4

### CREATE NEW USER
POST {{base_url}}/auth/signup
Content-Type: application/json

{
  "username": "matheustorres",
  "email": "matheustorres@email.com",
  "password": "secret",
  "fullName": "Matheus Torres",
  "phoneNumber": "79999999999",
  "cpf": "12345678979",
  "imageUrl": "matheus.png"
}

### GET ALL USERS
GET {{base_url}}/users

### GET ALL USER PAGINATION
GET {{base_url}}/users?size=&page=1

### GET BY USERTYPE
GET {{base_url}}/users?userType=STUDENT

### GET BY EMAIL
GET {{base_url}}/users?email=matheustorres@email.com

### GET BY CPF
GET {{base_url}}/users?userType=STUDENT&email=matheustorres@email.com

### GET USER BY ID
GET {{base_url}}/users/{{user_id}}

### DELETE USER
DELETE {{base_url}}/users/{{user_id}}

### UPDATE USER
PUT {{base_url}}/users/{{user_id}}
Content-Type: application/json

{
  "fullName": "Roberto Matheus Torres",
  "phoneNumber": "79999999998",
  "cpf": "22345678979"
}

### UPDATE PASSWORD
PUT {{base_url}}/users/{{user_id}}/password
Content-Type: application/json

{
  "password": "secret1",
  "oldPassword": "secret"
}

### UPDATE IMAGE
PUT {{base_url}}/users/{{user_id}}/image
Content-Type: application/json

{
  "imageUrl": "matheus123.png"
}